(setenv "GOPATH" "/home/cb/Projects/gopath")
(setenv "GOROOT" "/usr/local/go") 
(add-to-list 'load-path (concat (getenv "GOPATH") "/src/github.com/dougm/goflymake" ))
(setq exec-path (append exec-path (list (expand-file-name (concat (getenv "GOPATH") "/bin")))))
(setq exec-path (append exec-path (list (expand-file-name (concat (getenv "GOROOT") "/bin")))))
(add-hook 'before-save-hook #'gofmt-before-save)
(require 'go-mode-load)
; (require 'go-flymake)
(require 'go-flycheck)
(require 'go-autocomplete)
(require 'auto-complete-config)
(electric-pair-mode 1)
(yas-global-mode 1)
(ac-config-default)
