(add-to-list 'load-path (concat (getenv "GOPATH") "/src/github.com/dougm/goflymake" ))
(add-to-list 'load-path (concat *home-elisp-path* "/go-mode.el/"))
(setenv "GOPATH" "/Users/cb/Projects/gopath")
(setq exec-path (append exec-path (list (expand-file-name "/Users/cb/Projects/gopath/bin"))))
(add-hook 'before-save-hook #'gofmt-before-save)
(require 'go-mode-load)
(require 'go-flymake)
(require 'go-flycheck)
(require 'go-autocomplete)
(require 'auto-complete-config)
(ac-config-default)
